name: Build main.py with PyInstaller and uv

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller
        run: pyinstaller --onefile --name xxl-mepay main.py

      - name: Verify build output
        run: dir dist\

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: dist/xxl-mepay.exe
